### BEGIN INIT INFO
# Provides: bluetooth-agent
# Required-Start: $remote_fs $syslog bluetooth
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Makes Bluetooth discoverable and connectable
# Description: Start Bluetooth-Agent at boot time.
### END INIT INFO
#! /bin/sh
# /etc/init.d/bluetooth-agent

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DESC="Start Bluetooth-Agent at boot time"
NAME="bluetooth-agent"
DAEMON="/usr/sbin/$NAME"

USER=root
HOME=/root
export USER HOME

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

case "$1" in
start)
	echo "Setting bluetooth discoverable"
	hciconfig hci0 piscan
	start-stop-daemon -S -x $DAEMON -b -- $PIN
	echo "bluetooth-agent started with pw: $PIN"
	;;
stop)
	echo "Stopping bluetooth-agent"
	start-stop-daemon -K -x $DAEMON
	;;
*)
	echo "Usage: /etc/init.d/bluetooth-agent {start|stop}"
	exit 1
	;;
esac

exit 0
