#!/bin/sh
### BEGIN INIT INFO
# Provides:          bluetooth
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Bluez4 bluetooth daemon
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin

case "$1" in
    start)
	echo -n "Starting bluetooth daemon: "
	start-stop-daemon -S -x /usr/sbin/bluetoothd
	if [ $? = 0 ]; then
	    echo "succeeded."
	else
	    echo "(failed.)"
	fi
	;;
    stop)
	echo -n "Stopping bluetooth daemon: "
	start-stop-daemon -K \
		-x /usr/sbin/bluetoothd
	echo "succeeded."
	;;
    restart|force-reload) 
	$0 stop
	$0 start
	exit
	;;
    *)
	echo "Usage: /etc/init.d/bluetooth {start|stop|restart|force-reload}"
	exit 1
	;;
esac

exit 0
